version: '3'
services:
   jenkins_internal:
        restart: always
        build: .
        volumes:
           - './jenkins_home:/var/jenkins_home'
           - '/var/run/docker.sock:/var/run/docker.sock'
        ports:
            - '82:8080'
            - '50000:50000'
